#ifndef GET_VOLUMES_LIST_H
#define GET_VOLUMES_LIST_H

#include <ntifs.h>
#pragma warning(disable:4996)

#include "dlp_enum.h"

/*
    연결리스트
*/
// 현 디바이스 드라이브 기억하는 연결리스트 
typedef struct ALL_DEVICE_DRIVES {

    PUCHAR Previous_Node;

    UNICODE_STRING DRIVE_ALPHABET;
    UNICODE_STRING DRIVE_NT_PATH; // 기준 
    DEVICE_DECTECT_ENUM DRIVE_DEVICE_TYPE; // 자체 개발 enum

    UNICODE_STRING USBSTOR_Serial; // USB인 경우, 이게 기준. 
    UNICODE_STRING USB_PDO_obj; // PNP 마운트된 USB 디바이스. ( 주로 Node Remove용 )

    PUCHAR Next_Node;

}ALL_DEVICE_DRIVES, * PALL_DEVICE_DRIVES;

extern PALL_DEVICE_DRIVES ALL_DEVICE_DRIVES_Start_Node; // 총 드라이브 연결리스트 시작노드 
extern PALL_DEVICE_DRIVES ALL_DEVICE_DRIVES_Current_Node; // 총 드라이브 연결리스트 현재노드 

PALL_DEVICE_DRIVES Create_ALL_DEVICE_DRIVES_Node(PUCHAR Previous_addr, PUNICODE_STRING DRIVE_ALPHABET, PUNICODE_STRING DRIVE_NT_PATH, PUNICODE_STRING USB_Serial, PDEVICE_DECTECT_ENUM DRIVE_DEVICE_TYPE);// 노드 생성
PALL_DEVICE_DRIVES Append_ALL_DEVICE_DRIVES_Node(PALL_DEVICE_DRIVES current_Node, PUNICODE_STRING DRIVE_ALPHABET, PUNICODE_STRING DRIVE_NT_PATH, PUNICODE_STRING USB_Serial, PDEVICE_DECTECT_ENUM DRIVE_DEVICE_TYPE);

//print
VOID Print_ALL_DEVICE_DRIVES_Node(PALL_DEVICE_DRIVES Start_Node);

//finder hint를 통하여 노드 추출 없으면 NULL반환
PALL_DEVICE_DRIVES Finder_ALL_DEVICE_DRIVES_Node(PALL_DEVICE_DRIVES Start_Node, PUNICODE_STRING IMPORTANT_DRIVE_NT_PATH_hint, PUNICODE_STRING Serial_Number_hint, PDEVICE_DECTECT_ENUM Option_INPUT_DRIVE_DEVICE_TYPE);

//업데이트
PALL_DEVICE_DRIVES Update_ALL_DEVICE_DRIVES_Node(PALL_DEVICE_DRIVES Spectified_Node_valid, PUNICODE_STRING DRIVE_ALPHABET, PDEVICE_DECTECT_ENUM DRIVE_DEVICE_TYPE);// 노드 수정

//특정-노드 삭제 
BOOLEAN Remove_Specified_ALL_DEVICE_DRIVES_Node(PALL_DEVICE_DRIVES* Start_Node, PALL_DEVICE_DRIVES* Current_Node, PALL_DEVICE_DRIVES Specified_Node);


// 마무리 함수, 중복 및 필요없는 노드는 지워야함
BOOLEAN Complete_ALL_DEVICE_DRIVED_Node(PALL_DEVICE_DRIVES* Start_Node, PALL_DEVICE_DRIVES* Current_Node);



#endif